### ISSUE TITLE
When you add a progress bar and a historical data transfer ?

### ISSUE THREAD

**Issue by ruCyberPoison** [MrDoobPG/BlitzUI#2]
Hello DrDoobPG i would like to know when you add a progress bar and a historical data transfer like on blitzui previous version (V6) i think is a great idea to put the progress bar with that tiny icon that told which speed i'm in, that truck and etc...

Please thank you to reply me. I also would like to know where can i found the old Blitzui allready mentioned before.

Rgds

**Comment by MrDoobPG** [comment]
This repo is very old and not up to date anymore, as it is not really needed any more, the interface or the page will be completely redesigned straight, the layout will change drastically, but no progressbar or history will be built in, just a certain one  Number of lines are made visible, otherwise the log would simply be too long and use too much memory, I / we are looking for performance, and as little as we can possibly lied, every log is a security hole in my eyes, but I'm sorry  it will not happen.  I hope you understand it
